<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMpexkpq\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMpexkpq/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMpexkpq.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMpexkpq\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerMpexkpq\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Mpexkpq',
    'container.build_id' => '6a6762b4',
    'container.build_time' => 1524603477,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMpexkpq');
